### ISSUE TITLE
POST /opds error 400

### ISSUE THREAD

**Issue by nicolaburetta** [intesys/openhospital-api#14]
Payload:
{
  "date": "2022-01-27T10:42:00.000Z",
  "complaint": "",
  "disease": {
    "code": 28,
    "description": "Abortions",
    "diseaseType": {
      "code": "MP",
      "description": "3.MATERNAL AND PERINATAL DISEASES"
    },
    "opdInclude": true,
    "ipdInInclude": true,
    "ipdOutInclude": true,
    "lock": 0
  },
  "disease2": false,
  "disease3": null,
  "note": "",
  "patientCode": 5,
  "age": 35,
  "sex": "M",
  "userID": "admin",
  "visitDate": "2022-01-27T10:42:00.000Z"
}

Response:
not available

Filling the disease2 field there are no errors.
I see that `disease2 = false` and `disease3 = null`. Maybe the api does not accept a boolean value?

**Comment by kledis-pashaj-comdata** [comment]
Problem on the request. Both disease2 and disease2 fields are objects of type DiseaseDTO and not booleans.
