### ISSUE TITLE
Add new "operation" apis

### ISSUE THREAD

**Issue by alefalezza** [intesys/openhospital-api#23]
We need CRUD api to manage operations by patient.
Ref: https://openhospital.atlassian.net/browse/OP-794

In the patient dashboard, we need to list all operation for a given patient, even if it's in or out. We found it probably can be found by joining table operationrow to admission and opd, and then to patient.

TODO: analyze

**Comment by kledis-pashaj-comdata** [comment]
GET and DELETE operation rows by patient were added
