### ISSUE TITLE
OpdDTO: Split Note field

### ISSUE THREAD

**Issue by axelpezzo** [intesys/openhospital-api#27]
We should update the OpdDTO in order to split the note field into those fields:

Reasons for entry;
Anamnesis;
Allergies;
Current therapies;
Prescriptions.

**Comment by alefalezza** [comment]
@ArnaudFonzam please align with Steve for designing the openapi spec.

**Comment by kledis-pashaj-comdata** [comment]
@ArnaudFonzam @alefalezza Are the openapi spec. ready?

**Comment by uni2grow** [comment]
yep is already available on branch feature/main/27

**Comment by alefalezza** [comment]
Moved to https://openhospital.atlassian.net/browse/OH2-20
